all: server_select client_select test_select

server_select:
	gcc server_select.c -o server_select
client_select:
	gcc client_select.c -o client_select
test_select:
	gcc test_select.c -o test_select
clean:
	rm -f server_select client_select test_select
	